### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Javran** [KC3Kai/kc3-icons#1]
got following error:
```
[time omitted...] PHP Warning:  file_put_contents(ships/664.swf): failed to open stream: No such file or directory in <path omitted>/kc3-icons/swf/swf.php on line 6
```
it stops generating errors after creating directory `swf/ships` .. you might want to keep an empty file under `swf/ships` so it can be tracked by git.

**Comment by dragonjet** [comment]
ayy, this is one of the things I'll fix this weekend
